### ISSUE TITLE
Letak social media links

### ISSUE THREAD

**Issue by mujahidfa** [speaktousdev/speaktous-website#33]
Right now in the website takde any links to our social media (Instagram, Facebook and our newly made Twitter). We should've had this a long time ago, tak tau macam mana boleh terlepas lol.

There's 2 places aku rasa boleh letak benda ni:
1. Dalam **About page**
2. Kat **Footer**

Maybe we'll need a bit of redesign by @areysimu for the About page to include the social media links on the page?

**Comment by mujahidfa** [comment]
Added social media links in the footer in #40 .

**Comment by rizahassan** [comment]
Social media links have been added
