### ISSUE TITLE
Sqip loader issue on M1 Mac

### ISSUE THREAD

**Issue by rizahassan** [speaktousdev/speaktous-website#45]
<img width="1391" alt="Screen Shot 2021-03-20 at 12 09 49 AM" src="https://user-images.githubusercontent.com/55040840/111859682-98255e80-8910-11eb-88b9-bb666f141bee.png">

![image](https://user-images.githubusercontent.com/55040840/111859741-02d69a00-8911-11eb-9d59-229b9575026d.png)

Failed to compile on M1 Macbook.

**Comment by mujahidfa** [comment]
Resolved with #47.
